from datetime import datetime
from typing import Optional
from sqlalchemy import String, Text, DateTime, ForeignKey, Boolean, Integer, JSON, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base, TimestampMixin, generate_uuid


class RedFlag(Base):
    """
    Warning signs detected during analysis.
    Linked to the scorecard run that found them.
    APPEND-ONLY — new flags inserted per run, never updated.

    Severities:  HIGH | MEDIUM | LOW
    Categories:  FINANCIAL | FILING | MANAGEMENT | MACRO
    
    Common flag_types:
        DECLINING_FCF           Free cash flow declining 3+ consecutive periods
        REVENUE_MARGIN_DIVERGE  Revenue growing but margins shrinking
        HIGH_DEBT_RISING_RATES  High D/E ratio in rising interest rate environment
        INSIDER_SELLING         Significant insider selling while promoting growth
        GOODWILL_IMPAIRMENT     Goodwill writedown (signals bad acquisition)
        AUDITOR_CHANGE          Auditor changed (potential red flag)
        QUALIFIED_OPINION       Auditor issued qualified/adverse opinion
        EARNINGS_QUALITY        Net income >> Free cash flow (aggressive accruals)
        CUSTOMER_CONCENTRATION  Few customers = high revenue concentration risk
        LEGAL_PROCEEDINGS       Material legal proceedings in 10-K risk factors
    """
    __tablename__ = "red_flags"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    ticker: Mapped[str] = mapped_column(String(10), ForeignKey("companies.ticker"), nullable=False)
    scorecard_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("scorecards.id"))
    session_id: Mapped[Optional[str]] = mapped_column(String(100))

    severity: Mapped[str] = mapped_column(String(10), nullable=False)       # HIGH, MEDIUM, LOW
    category: Mapped[str] = mapped_column(String(50), nullable=False)       # FINANCIAL, FILING etc.
    flag_type: Mapped[str] = mapped_column(String(100), nullable=False)     # standardized slug
    title: Mapped[str] = mapped_column(String(255), nullable=False)         # human-readable short title
    description: Mapped[str] = mapped_column(Text, nullable=False)          # full explanation
    evidence: Mapped[Optional[str]] = mapped_column(Text)                   # data point that triggered this
    source: Mapped[str] = mapped_column(String(20), nullable=False)         # FINANCIAL_DATA, SEC_FILING, NEWS

    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Relationships
    scorecard: Mapped["Scorecard"] = relationship(back_populates="red_flags")

    def __repr__(self) -> str:
        return f"<RedFlag ticker={self.ticker} severity={self.severity} type={self.flag_type}>"


class ChatSession(Base, TimestampMixin):
    """
    Stores full conversation history per session.
    session_id is a UUID generated by the client on first request.
    Tied to a specific company and the scorecard that initiated the analysis.

    messages JSONB structure:
    [
        {"role": "user", "content": "Analyze Apple", "timestamp": "..."},
        {"role": "assistant", "content": "...", "timestamp": "...", "node": "scorer_node"}
    ]
    """
    __tablename__ = "chat_sessions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    session_id: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    ticker: Mapped[str] = mapped_column(String(10), ForeignKey("companies.ticker"), nullable=False)
    scorecard_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("scorecards.id"))

    messages: Mapped[Optional[dict]] = mapped_column(JSON)                  # full conversation array
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    company: Mapped["Company"] = relationship(back_populates="chat_sessions")
    scorecard: Mapped[Optional["Scorecard"]] = relationship(back_populates="chat_sessions")

    def __repr__(self) -> str:
        return f"<ChatSession session_id={self.session_id} ticker={self.ticker}>"


class CompetitorMapping(Base, TimestampMixin):
    """
    Many-to-many relationship between companies for competitor comparison.
    source = AUTO  → detected by same sector/industry from FMP
    source = MANUAL → user explicitly added via /compare endpoint
    """
    __tablename__ = "competitor_mappings"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    ticker: Mapped[str] = mapped_column(String(10), ForeignKey("companies.ticker"), nullable=False)
    competitor_ticker: Mapped[str] = mapped_column(String(10), ForeignKey("companies.ticker"), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False)         # AUTO or MANUAL

    # Relationships
    company: Mapped["Company"] = relationship(
        foreign_keys=[ticker], back_populates="competitor_mappings"
    )
    competitor: Mapped["Company"] = relationship(
        foreign_keys=[competitor_ticker]
    )

    def __repr__(self) -> str:
        return f"<CompetitorMapping {self.ticker} → {self.competitor_ticker} ({self.source})>"


class DataFetchLog(Base):
    """
    Audit trail for every external API call made.
    Used by cache_manager to decide what needs re-fetching.

    Freshness rules:
        SEC 10-K filing   → re-fetch if not fetched this fiscal year
        SEC 10-Q filing   → re-fetch if not fetched this quarter
        FINANCIALS annual → re-fetch if older than 90 days
        FINANCIALS ratios → re-fetch if older than 24 hours
        NEWS              → always fetch fresh (never cached)

    data_types:
        FILING_10K | FILING_10Q | FINANCIALS_ANNUAL
        FINANCIALS_QUARTERLY | PRICE | NEWS
    """
    __tablename__ = "data_fetch_log"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    ticker: Mapped[str] = mapped_column(String(10), ForeignKey("companies.ticker"), nullable=False)
    source: Mapped[str] = mapped_column(String(30), nullable=False)         # YFINANCE, FMP, SEC_EDGAR, NEWSAPI
    data_type: Mapped[str] = mapped_column(String(50), nullable=False)      # see docstring above
    status: Mapped[str] = mapped_column(String(20), nullable=False)         # SUCCESS, FAILED, PARTIAL
    records_fetched: Mapped[Optional[int]] = mapped_column(Integer)
    error_message: Mapped[Optional[str]] = mapped_column(Text)              # NULL if SUCCESS
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Relationships
    company: Mapped["Company"] = relationship(back_populates="fetch_logs")

    def __repr__(self) -> str:
        return f"<DataFetchLog ticker={self.ticker} source={self.source} status={self.status}>"


# Indexes
Index("idx_red_flags_ticker", RedFlag.ticker)
Index("idx_red_flags_scorecard", RedFlag.scorecard_id)
Index("idx_red_flags_type", RedFlag.ticker, RedFlag.flag_type)
Index("idx_chat_sessions_session_id", ChatSession.session_id)
Index("idx_competitor_ticker", CompetitorMapping.ticker)
Index("idx_fetch_log_lookup", DataFetchLog.ticker, DataFetchLog.data_type, DataFetchLog.fetched_at)
